#!/bin/bash

while getopts d:s o
do	case "$o" in
	d)	reqArgs="$OPTARG";;
	s)	sopt="hello word";;
	[?])	print >&2 "Usage: $0 [-s] [-d seplist] file ..."
		exit 1;;
	esac
done
shift $OPTIND-1

echo $reqArgs
